In [4]:
import pandas as pd
data = pd.read_csv('Advertising.csv')
data

X = data.drop(columns=['Unnamed: 0','sales'])
y = ['sales']

In [5]:
X

        TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]